#!/bin/bash


# System info
sys_name="\"uname -n\""
kernel="\"uname -r -m\""
time_up="\"uptime | cut -c 14-25\""

# Memory
ram_mem="\"free -h | grep Mem | cut -c 15-21,40-44,71-80\""

# File system
files_sys_home="\"df -h | grep root | cut -c 17-46\""

# CPU 
freq="\"cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq\""

volt="\"vcgencmd measure_volts | cut -c 6-13\""
temperature="\"vcgencmd measure_temp | cut -c 6-12\""

# Display
get_display_pos="\"echo \$DISPLAY\""


    echo "$sys_name" > raspinfo.txt
    echo "$kernel" >> raspinfo.txt
    echo "$time_up" >> raspinfo.txt
    echo "$ram_mem" >> raspinfo.txt
    echo "$files_sys_home" >> raspinfo.txt
    echo "$freq" >> raspinfo.txt
    echo "$volts" >> raspinfo.txt
    echo "$temperature" >> raspinfo.txt
    echo "$get_display_pos" >> raspinfo.txt
    
